### ISSUE TITLE
Support LOW_PRIORITY in dumpling

### ISSUE THREAD

**Issue by niezefeng** [pingcap/dumpling#289] opened 2021-06-03 10:17 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**
When using the mydumper, the SQL will add the LOW_PRIORITY hint automatically. 
e.g.
```
SELECT /*!40001 LOW_PRIORITY SQL_NO_CACHE */ * FROM `test`.`sbtest1`;
```
But dumpling doesn't support this.

**Describe the feature you'd like:**
Add an option to add hint LOW_PRIORITY for all the SQLs. This could help to reduce the impact on online txns in tidb v3 or lower version.

**Comment by kennytm** [comment] 2021-06-10 09:10
Duplicate of https://github.com/pingcap/dumpling/issues/115#issuecomment-714355349.

**Closed by kennytm** 2021-06-10 09:10 UTC
