### ISSUE TITLE
dumpling leads to tidb oom

### ISSUE THREAD

**Issue by hunkliu27** [pingcap/dumpling#238] opened 2021-02-07 10:16 UTC
## Question

Execute dumpling interrupt and report an error, “invalid connection”, as shown in the figure below
![image](https://user-images.githubusercontent.com/43460483/107143328-77600580-696f-11eb-9bc9-59594116a90c.png)

After checking the system log, TIDB OOM was found, and the error was reported as shown in the figure
![image](https://user-images.githubusercontent.com/43460483/107143394-c73ecc80-696f-11eb-8fce-81d5d9a77332.png)

Dumpling is executed in a test environment with 48GB of server memory. Dumpling is executed without any other operations.

Why does this happen? How can this be avoided?

**Comment by lichunzhu** [comment] 2021-03-08 07:27
You can specify a `--rows` argument and try it again. Without this TiDB will select the whole database which will cause a lot of memory.
You can refer to https://docs.pingcap.com/tidb/dev/dumpling-overview#control-the-memory-usage-of-exporting-large-tables for more solutions.

**Comment by lichunzhu** [comment] 2021-03-25 12:20
duplicate of https://github.com/pingcap/dumpling/issues/232. Feel free to open this again if you find any further problems.

**Closed by lichunzhu** 2021-03-25 12:20 UTC
